# Generated by Django 5.1.3 on 2024-11-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(choices=[('Программист', 'Программист'), ('Менеджер проекта', 'Менеджер проекта'), ('Инженер-программист', 'Инженер-программист'), ('Дизайнер UX/UI', 'Дизайнер UX/UI'), ('Data Scientist', 'Data Scientist'), ('Аналитик данных', 'Аналитик данных'), ('Тестировщик ПО', 'Тестировщик ПО'), ('DevOps-инженер', 'DevOps-инженер'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Backend-разработчик', 'Backend-разработчик'), ('Fullstack-разработчик', 'Fullstack-разработчик'), ('Системный администратор', 'Системный администратор'), ('Специалист по кибербезопасности', 'Специалист по кибербезопасности'), ('Менеджер по продажам', 'Менеджер по продажам'), ('Маркетолог', 'Маркетолог'), ('Бухгалтер', 'Бухгалтер'), ('Юрист', 'Юрист'), ('HR-менеджер', 'HR-менеджер'), ('Руководитель проекта', 'Руководитель проекта'), ('Архитектор ПО', 'Архитектор ПО')], max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Навык'),
        ),
    ]
