# Generated by Django 5.1.3 on 2024-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_resume_position_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
    ]
